# Generated by Django 5.1.7 on 2025-03-27 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('initials', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tutorial', 'Tutorial'), ('Technical Task', 'Technical Task'), ('User Story', 'User Story')], max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('urgent', 'urgent')], max_length=10)),
                ('status', models.CharField(choices=[('todo', 'todo'), ('inprogress', 'inprogress'), ('awaitfeedback', 'awaitfeedback'), ('done', 'done')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('assigned', models.ManyToManyField(blank=True, related_name='tasks', to='join_app.contact')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTaskName', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='join_app.task')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('initials', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('contacts', models.ManyToManyField(related_name='users', to='join_app.contact')),
            ],
        ),
    ]
