# Generated by Django 5.1.6 on 2025-03-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='todo', max_length=255),
        ),
    ]
