# Generated by Django 5.1.6 on 2025-03-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='status',
            new_name='done',
        ),
    ]
