# Generated by Django 5.1.7 on 2025-03-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_remove_subtask_task_task_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='users', to='join_app.contact'),
        ),
    ]
