# Generated by Django 5.1.6 on 2025-03-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_rename_status_subtask_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='title',
            new_name='subTaskName',
        ),
    ]
