# Generated by Django 5.1.7 on 2025-04-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_alter_user_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='userId',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
