# Generated by Django 5.1.7 on 2025-03-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_alter_user_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='users', to='join_app.task'),
        ),
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
