# Generated by Django 5.1.7 on 2025-04-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_task_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='userId',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
