# Generated by Django 5.1.6 on 2025-03-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_rename_title_subtask_subtaskname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='description',
        ),
    ]
