# Generated by Django 5.1.7 on 2025-04-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_contact_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
