# Generated by Django 5.1.7 on 2025-04-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0008_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned',
        ),
    ]
