# Generated by Django 5.1.7 on 2025-04-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0011_remove_task_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='join_app.contact'),
        ),
    ]
