# Generated by Django 5.1.7 on 2025-04-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0012_task_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.JSONField(default=list),
        ),
    ]
