# Generated by Django 5.1.7 on 2025-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0013_remove_task_assigned_task_assigned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned',
        ),
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='user_contacts', to='join_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='task_users', to='join_app.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='join_app.user'),
        ),
    ]
